vec3 a_position  : POSITION; 
vec3 a_normal    : NORMAL; 
vec4 i_data0    : TEXCOORD7; 
vec4 i_data1    : TEXCOORD6; 
vec4 i_data2    : TEXCOORD5; 
vec4 i_data3    : TEXCOORD4; 
vec3 v_normal : TEXCOORD0; 
vec4 v_color : TEXCOORD1; 
float v_viewDepth : TEXCOORD2; 
